### PR TITLE
Update react version

### PR DESCRIPTION
**Pull request by krismp**
Update react version to work with react version 15

### CODE REVIEW

**Comment by imchuck** [comment]
@dlau Are you gonna accept this pull request? Thanks

**Comment by dlau** [comment]
Hi, really sorry about this. I have been caught up between jobs for the past month and won't have time to properly maintain this package for the foreseeable future.

Would someone be interested in taking ownership of this?

Thank you.
Daryl

**Comment by imchuck** [comment]
@dlau Thanks for this. Is this already updated on npm?

**Comment by dlau** [comment]
Hi , just bumped and published to v0.3.0

**Comment by imchuck** [comment]
@dlau Thanks. We've just updated the npm in our application. Our team could mantain this if you want. Please let us know if we can help you in something else.

**Comment by dlau** [comment]
@imchuck Sounds great. I'll set you guys up later today.

Would you prefer me to add you as a collaborator or to transfer the repo?

Thank you.

**Comment by imchuck** [comment]
As you wish. If you don't like to transfer the repo, is ok to add me just as collaborator. :)
Thanks for your trust.

**Comment by dlau** [comment]
Added you as a collaborator in this repo.

Hope this is you too (npm permissions):
https://www.npmjs.com/~imchuck

**Pull request merged**
